version: '3'
services:
  server:
    container_name: python_server
    ipc: "shareable"
    build: server/
    network_mode: host
  node:
    container_name: python_node
    ipc: "service:server"
    build: node/
    network_mode: host